name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: zephyr_ldc_examples

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr_ldc_examples
          toolchains: arm-zephyr-eabi

      - name: Setup D
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ldc

      - name: Build firmware
        working-directory: zephyr_ldc_examples
        shell: bash
        run: |
          west build -b qemu_cortex_m3 pthread
          west twister -T pthread -W -j 1 -v
